### ISSUE TITLE
Success massage show as floating massage. 

### ISSUE THREAD

**Issue by Mspiro** [Libbna/CUSTOM-CMS#199]
For now message shows like this: 
![image](https://user-images.githubusercontent.com/32816725/148973169-e242976b-e551-4f11-9742-b917100a036c.png)
 this message theme affect to other content theme. 
To solve this message  should be show as flating message  .

**Comment by Libbna** [comment]
Requirement: The issue facing with alert message is after adding a content, or login, etc. We get this success alert. We click on the close button to close the alert but if the page reloads it again pops-up. 

To solve this: @Mspiro  suggested - we can use floating message instead of alert or we can set a cookie.
